from __future__ import annotations

import os
import shutil
import subprocess
import sys
import queue
import threading
import tkinter as tk
from pathlib import Path
from tkinter import filedialog, messagebox, ttk

from .generator import generate_gui_code
from .parser import ScriptSpec, parse_script


TEXT = {
    "zh": {
        "title": "Python 脚本转 GUI",
        "script_frame": "1. 选择 Python 命令行脚本",
        "output_frame": "2. 输出目录",
        "browse": "选择",
        "analyze": "分析",
        "generate": "生成 GUI 工程",
        "detected_args": "识别到的参数",
        "log": "日志",
        "build_exe": "打包当前生成工程为 exe",
        "language": "语言",
        "error": "错误",
        "select_existing": "请选择存在的 .py 文件",
        "analyze_failed": "分析失败",
        "output_missing": "请选择输出目录",
        "generate_failed": "生成失败",
        "done": "完成",
        "generated_project": "已生成 GUI 工程：\n{path}",
        "build_missing_spec": "请先生成工程",
        "build_script_missing": "未找到生成工程里的 build_exe.ps1",
        "log_detected": "识别到 {count} 个参数，脚本类型：{kind}。",
        "log_generated": "已生成工程：{path}",
        "log_building": "开始打包：{path}",
        "log_build_exit": "打包进程退出码：{code}",
        "log_build_failed": "打包失败：{error}",
        "columns": ("名称", "类型", "参数名", "默认值", "值类型"),
        "file_title": "选择 Python 脚本",
        "dir_title": "选择输出目录",
    },
    "en": {
        "title": "Python Script to GUI",
        "script_frame": "1. Select Python CLI script",
        "output_frame": "2. Output folder",
        "browse": "Browse",
        "analyze": "Analyze",
        "generate": "Generate GUI project",
        "detected_args": "Detected arguments",
        "log": "Log",
        "build_exe": "Build selected generated project exe",
        "language": "Language",
        "error": "Error",
        "select_existing": "Please select an existing .py file",
        "analyze_failed": "Analyze failed",
        "output_missing": "Please choose output folder",
        "generate_failed": "Generate failed",
        "done": "Done",
        "generated_project": "Generated GUI project:\n{path}",
        "build_missing_spec": "Generate a project first",
        "build_script_missing": "Generated build_exe.ps1 not found",
        "log_detected": "Detected {count} arguments as {kind}.",
        "log_generated": "Generated project: {path}",
        "log_building": "Building exe with {path}",
        "log_build_exit": "Build exited with code {code}",
        "log_build_failed": "Build failed: {error}",
        "columns": ("name", "kind", "options", "default", "type"),
        "file_title": "Select Python script",
        "dir_title": "Select output folder",
    },
}


def build_project_name(script_path: str) -> str:
    return Path(script_path).stem + "_gui"


def analyze_script(path: str) -> ScriptSpec:
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        source = handle.read()
    return parse_script(source, script_path=os.path.abspath(path))


def write_gui_project(spec: ScriptSpec, output_root: str) -> Path:
    project_name = build_project_name(spec.script_path)
    project_dir = Path(output_root) / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    target_script = project_dir / Path(spec.script_path).name
    if Path(spec.script_path).resolve() != target_script.resolve():
        shutil.copy2(spec.script_path, target_script)

    local_spec = ScriptSpec(
        script_path=str(target_script),
        script_type=spec.script_type,
        arguments=spec.arguments,
    )
    gui_file = project_dir / f"{project_name}.py"
    gui_file.write_text(generate_gui_code(local_spec), encoding="utf-8")

    build_script = project_dir / "build_exe.ps1"
    build_script.write_text(
        "$ErrorActionPreference = \"Stop\"\n"
        "Set-Location -LiteralPath $PSScriptRoot\n"
        "python -m PyInstaller --noconfirm --onefile --windowed "
        f"--name {project_name} .\\{project_name}.py\n"
        f"Write-Host \"Build complete: $PSScriptRoot\\dist\\{project_name}.exe\"\n",
        encoding="utf-8",
    )

    readme = project_dir / "README.md"
    readme.write_text(
        f"# {project_name}\n\n"
        "This project was generated by py2gui_tool.\n\n"
        "## Run\n\n"
        f"```powershell\npython .\\{project_name}.py\n```\n\n"
        "## Build exe\n\n"
        "```powershell\n.\\build_exe.ps1\n```\n",
        encoding="utf-8",
    )
    return project_dir


class Py2GuiApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Python Script to GUI")
        self.geometry("980x700")
        self.minsize(860, 580)

        self.script_path = tk.StringVar()
        self.output_dir = tk.StringVar(value=str(Path.cwd()))
        self.language = tk.StringVar(value="zh")
        self.current_spec: ScriptSpec | None = None
        self.log_queue = queue.Queue()
        self.i18n_widgets = {}

        self._build_ui()
        self._apply_language()
        self.after(100, self._drain_log_queue)

    def _t(self, key: str) -> str:
        return TEXT[self.language.get()].get(key, key)

    def _build_ui(self):
        root = ttk.Frame(self, padding=10)
        root.pack(fill=tk.BOTH, expand=True)

        lang_bar = ttk.Frame(root)
        lang_bar.pack(fill=tk.X)
        self.language_label = ttk.Label(lang_bar)
        self.language_label.pack(side=tk.LEFT)
        self.language_combo = ttk.Combobox(
            lang_bar,
            textvariable=self.language,
            values=["zh", "en"],
            width=10,
            state="readonly",
        )
        self.language_combo.pack(side=tk.LEFT, padx=(8, 0))
        self.language_combo.bind("<<ComboboxSelected>>", lambda _event: self._apply_language())

        script_frame = ttk.LabelFrame(root, padding=8)
        script_frame.pack(fill=tk.X)
        self.script_frame = script_frame
        ttk.Entry(script_frame, textvariable=self.script_path).pack(side=tk.LEFT, fill=tk.X, expand=True)
        self.script_browse_btn = ttk.Button(script_frame, command=self._choose_script)
        self.script_browse_btn.pack(side=tk.LEFT, padx=(8, 0))
        self.analyze_btn = ttk.Button(script_frame, command=self._analyze)
        self.analyze_btn.pack(side=tk.LEFT, padx=(8, 0))

        out_frame = ttk.LabelFrame(root, padding=8)
        out_frame.pack(fill=tk.X, pady=(10, 0))
        self.out_frame = out_frame
        ttk.Entry(out_frame, textvariable=self.output_dir).pack(side=tk.LEFT, fill=tk.X, expand=True)
        self.out_browse_btn = ttk.Button(out_frame, command=self._choose_output_dir)
        self.out_browse_btn.pack(side=tk.LEFT, padx=(8, 0))
        self.generate_btn = ttk.Button(out_frame, command=self._generate)
        self.generate_btn.pack(side=tk.LEFT, padx=(8, 0))

        preview_frame = ttk.LabelFrame(root, padding=8)
        preview_frame.pack(fill=tk.BOTH, expand=True, pady=(10, 0))
        self.preview_frame = preview_frame
        columns = ("name", "kind", "options", "default", "type")
        self.tree = ttk.Treeview(preview_frame, columns=columns, show="headings", height=10)
        for col in columns:
            self.tree.heading(col, text=col)
            self.tree.column(col, width=140 if col != "options" else 240, anchor=tk.W)
        self.tree.pack(fill=tk.BOTH, expand=True)

        log_frame = ttk.LabelFrame(root, padding=8)
        log_frame.pack(fill=tk.BOTH, expand=True, pady=(10, 0))
        self.log_frame = log_frame
        self.log = tk.Text(log_frame, height=8, wrap=tk.WORD)
        self.log.pack(fill=tk.BOTH, expand=True)

        buttons = ttk.Frame(root)
        buttons.pack(fill=tk.X, pady=(10, 0))
        self.build_btn = ttk.Button(buttons, command=self._build_generated_exe)
        self.build_btn.pack(side=tk.LEFT)

    def _apply_language(self):
        self.title(self._t("title"))
        self.language_label.configure(text=self._t("language"))
        self.script_frame.configure(text=self._t("script_frame"))
        self.out_frame.configure(text=self._t("output_frame"))
        self.script_browse_btn.configure(text=self._t("browse"))
        self.out_browse_btn.configure(text=self._t("browse"))
        self.analyze_btn.configure(text=self._t("analyze"))
        self.generate_btn.configure(text=self._t("generate"))
        self.preview_frame.configure(text=self._t("detected_args"))
        self.log_frame.configure(text=self._t("log"))
        self.build_btn.configure(text=self._t("build_exe"))
        for col, label in zip(("name", "kind", "options", "default", "type"), self._t("columns")):
            self.tree.heading(col, text=label)

    def _choose_script(self):
        path = filedialog.askopenfilename(title=self._t("file_title"), filetypes=[("Python", "*.py"), ("All files", "*.*")])
        if path:
            self.script_path.set(path)
            self.output_dir.set(str(Path(path).parent))

    def _choose_output_dir(self):
        path = filedialog.askdirectory(title=self._t("dir_title"))
        if path:
            self.output_dir.set(path)

    def _analyze(self):
        path = self.script_path.get().strip()
        if not path or not Path(path).is_file():
            messagebox.showerror(self._t("error"), self._t("select_existing"))
            return
        try:
            self.current_spec = analyze_script(path)
        except Exception as exc:
            messagebox.showerror(self._t("analyze_failed"), str(exc))
            return
        self._render_spec(self.current_spec)
        self._log(self._t("log_detected").format(count=len(self.current_spec.arguments), kind=self.current_spec.script_type))

    def _generate(self):
        if self.current_spec is None:
            self._analyze()
        if self.current_spec is None:
            return
        output = self.output_dir.get().strip()
        if not output:
            messagebox.showerror(self._t("error"), self._t("output_missing"))
            return
        try:
            project_dir = write_gui_project(self.current_spec, output)
        except Exception as exc:
            messagebox.showerror(self._t("generate_failed"), str(exc))
            return
        self._log(self._t("log_generated").format(path=project_dir))
        messagebox.showinfo(self._t("done"), self._t("generated_project").format(path=project_dir))

    def _build_generated_exe(self):
        if self.current_spec is None:
            messagebox.showerror(self._t("error"), self._t("build_missing_spec"))
            return
        project_dir = Path(self.output_dir.get().strip()) / build_project_name(self.current_spec.script_path)
        build_script = project_dir / "build_exe.ps1"
        if not build_script.is_file():
            messagebox.showerror(self._t("error"), self._t("build_script_missing"))
            return
        threading.Thread(target=self._run_build_script, args=(build_script,), daemon=True).start()

    def _run_build_script(self, build_script: Path):
        self._log(self._t("log_building").format(path=build_script))
        args = ["powershell", "-ExecutionPolicy", "Bypass", "-File", str(build_script)]
        try:
            proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding="utf-8", errors="replace")
            assert proc.stdout is not None
            for line in proc.stdout:
                self.log_queue.put(line.rstrip())
            code = proc.wait()
            self.log_queue.put(self._t("log_build_exit").format(code=code))
        except Exception as exc:
            self.log_queue.put(self._t("log_build_failed").format(error=exc))

    def _render_spec(self, spec: ScriptSpec):
        for item in self.tree.get_children():
            self.tree.delete(item)
        for arg in spec.arguments:
            self.tree.insert("", tk.END, values=(arg.name, arg.kind, ", ".join(arg.option_strings), arg.default or "", arg.value_type))

    def _log(self, text: str):
        self.log.insert(tk.END, text + "\n")
        self.log.see(tk.END)

    def _drain_log_queue(self):
        try:
            while True:
                text = self.log_queue.get_nowait()
                self._log(text)
        except queue.Empty:
            pass
        self.after(100, self._drain_log_queue)


if __name__ == "__main__":
    app = Py2GuiApp()
    app.mainloop()
