from __future__ import annotations

import json
from dataclasses import asdict

from .parser import ScriptSpec


def generate_gui_code(spec: ScriptSpec) -> str:
    data = {
        "script_path": spec.script_path,
        "script_type": spec.script_type,
        "arguments": [asdict(arg) for arg in spec.arguments],
    }
    spec_json = json.dumps(data, ensure_ascii=False, indent=2)
    return f'''# Generated by py2gui_tool.
import json
import os
import subprocess
import sys
import queue
import threading
import tkinter as tk
from tkinter import filedialog, messagebox, ttk


SPEC = json.loads(r"""{spec_json}""")


class GeneratedGui(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(os.path.basename(SPEC["script_path"]) + " GUI")
        self.geometry("900x640")
        self.minsize(760, 520)
        self.widgets = {{}}
        self.process = None
        self.output_queue = queue.Queue()
        self._build()
        self.after(100, self._drain_output_queue)

    def _build(self):
        root = ttk.Frame(self, padding=10)
        root.pack(fill=tk.BOTH, expand=True)

        path_frame = ttk.LabelFrame(root, text="Script", padding=8)
        path_frame.pack(fill=tk.X)
        self.script_path = tk.StringVar(value=SPEC["script_path"])
        ttk.Entry(path_frame, textvariable=self.script_path).pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Button(path_frame, text="Browse", command=self._browse_script).pack(side=tk.LEFT, padx=(8, 0))

        args_frame = ttk.LabelFrame(root, text="Arguments", padding=8)
        args_frame.pack(fill=tk.X, pady=(10, 0))
        for row, arg in enumerate(SPEC["arguments"]):
            label = arg["name"]
            if arg["option_strings"]:
                label += " (" + ", ".join(arg["option_strings"]) + ")"
            ttk.Label(args_frame, text=label).grid(row=row, column=0, sticky=tk.W, padx=(0, 8), pady=4)
            if arg["kind"] == "flag":
                var = tk.BooleanVar(value=str(arg.get("default", "")).lower() in ("true", "1", "yes"))
                widget = ttk.Checkbutton(args_frame, variable=var)
                widget.grid(row=row, column=1, sticky=tk.W, pady=4)
                self.widgets[arg["name"]] = (arg, var)
            elif arg.get("choices"):
                var = tk.StringVar(value=arg.get("default") or "")
                widget = ttk.Combobox(args_frame, textvariable=var, values=arg["choices"], state="readonly")
                widget.grid(row=row, column=1, sticky=tk.EW, pady=4)
                self.widgets[arg["name"]] = (arg, var)
            else:
                var = tk.StringVar(value=arg.get("default") or "")
                widget = ttk.Entry(args_frame, textvariable=var)
                widget.grid(row=row, column=1, sticky=tk.EW, pady=4)
                self.widgets[arg["name"]] = (arg, var)
                if _looks_like_path(arg):
                    ttk.Button(args_frame, text="...", width=4, command=lambda v=var: self._browse_value(v)).grid(row=row, column=2, padx=(6, 0), pady=4)
        args_frame.columnconfigure(1, weight=1)

        cmd_frame = ttk.Frame(root)
        cmd_frame.pack(fill=tk.X, pady=(10, 0))
        self.run_button = ttk.Button(cmd_frame, text="Run", command=self._run)
        self.run_button.pack(side=tk.LEFT)
        self.stop_button = ttk.Button(cmd_frame, text="Stop", command=self._stop, state=tk.DISABLED)
        self.stop_button.pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(cmd_frame, text="Copy command", command=self._copy_command).pack(side=tk.LEFT, padx=(8, 0))

        output_frame = ttk.LabelFrame(root, text="Output", padding=8)
        output_frame.pack(fill=tk.BOTH, expand=True, pady=(10, 0))
        self.output = tk.Text(output_frame, wrap=tk.NONE)
        self.output.pack(fill=tk.BOTH, expand=True)

    def _browse_script(self):
        path = filedialog.askopenfilename(filetypes=[("Python", "*.py"), ("All files", "*.*")])
        if path:
            self.script_path.set(path)

    def _browse_value(self, var):
        path = filedialog.askopenfilename()
        if path:
            var.set(path)

    def _build_args(self):
        script = self.script_path.get().strip()
        args = [sys.executable, script]
        for name, (arg, var) in self.widgets.items():
            if arg["kind"] == "positional":
                value = var.get().strip()
                if value:
                    args.append(value)
            elif arg["kind"] == "flag":
                if var.get():
                    args.append(_primary_option(arg))
            else:
                value = var.get().strip()
                if value:
                    args.extend([_primary_option(arg), value])
        return args

    def _run(self):
        script = self.script_path.get().strip()
        if not script or not os.path.isfile(script):
            messagebox.showerror("Error", "Script path does not exist")
            return
        args = self._build_args()
        self.output.delete("1.0", tk.END)
        self.output.insert(tk.END, "Command: " + subprocess.list2cmdline(args) + "\\n\\n")
        self.run_button.configure(state=tk.DISABLED)
        self.stop_button.configure(state=tk.NORMAL)
        threading.Thread(target=self._run_worker, args=(args,), daemon=True).start()

    def _run_worker(self, args):
        try:
            self.process = subprocess.Popen(
                args,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
                creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0,
            )
            assert self.process.stdout is not None
            for line in self.process.stdout:
                self.output_queue.put(line)
            code = self.process.wait()
            self.output_queue.put("\\n[exit code: " + str(code) + "]\\n")
        except Exception as exc:
            self.output_queue.put("\\n[failed] " + str(exc) + "\\n")
        finally:
            self.output_queue.put("__DONE__")

    def _stop(self):
        if self.process and self.process.poll() is None:
            self.process.terminate()

    def _copy_command(self):
        self.clipboard_clear()
        self.clipboard_append(subprocess.list2cmdline(self._build_args()))

    def _drain_output_queue(self):
        try:
            while True:
                item = self.output_queue.get_nowait()
                if item == "__DONE__":
                    self.run_button.configure(state=tk.NORMAL)
                    self.stop_button.configure(state=tk.DISABLED)
                    self.process = None
                else:
                    self.output.insert(tk.END, item)
                    self.output.see(tk.END)
        except queue.Empty:
            pass
        self.after(100, self._drain_output_queue)


def _primary_option(arg):
    for opt in arg.get("option_strings", []):
        if opt.startswith("--"):
            return opt
    if arg.get("option_strings"):
        return arg["option_strings"][0]
    return "--" + arg["name"].replace("_", "-")


def _looks_like_path(arg):
    name = arg.get("name", "").lower()
    return "file" in name or "path" in name or "dir" in name or arg.get("value_type") in ("Path", "File")


if __name__ == "__main__":
    app = GeneratedGui()
    app.mainloop()
'''
